# Generated by Django 2.0.7 on 2018-07-31 21:09

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import main.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('numerico', models.NullBooleanField(verbose_name='Numérico')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Orden')),
                ('valor_texto', models.CharField(blank=True, max_length=255, verbose_name='Valor texto')),
                ('valor_numerico', models.IntegerField(blank=True, null=True, verbose_name='Valor numérico')),
                ('identificador', models.CharField(blank=True, max_length=255, verbose_name='Identificador')),
                ('automatico', models.NullBooleanField(verbose_name='Automático')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
            bases=(main.mixins.SerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izquierda', models.CharField(blank=True, max_length=255, verbose_name='Izquierda')),
                ('derecha', models.CharField(blank=True, max_length=255, verbose_name='Derecha')),
                ('tipo', models.CharField(blank=True, choices=[('>', 'Mayor que'), ('<', 'Menor que'), ('=', 'Igual que'), ('>=', 'Mayor o igual que'), ('<=', 'Menor o igual que'), ('<>', 'Diferente que'), ('+', 'Suma'), ('*', 'Multiplicación'), ('/', 'División'), ('-', 'Resta')], max_length=2, verbose_name='Tipo')),
                ('orden', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Orden')),
                ('uvt', models.NullBooleanField(verbose_name='UVT')),
                ('valor_si', models.CharField(blank=True, max_length=255, verbose_name='Valor SI')),
                ('valor_no', models.CharField(blank=True, max_length=255, verbose_name='Valor NO')),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_set', to='main.Campo', verbose_name='Campo')),
                ('condiciones', models.ManyToManyField(related_name='_condicion_condiciones_+', to='main.Condicion', verbose_name='Condiciones')),
            ],
            options={
                'verbose_name': 'Condición',
                'verbose_name_plural': 'Condiciones',
            },
            bases=(main.mixins.SerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('identificador', models.CharField(max_length=255, verbose_name='Identificador')),
                ('repetible', models.NullBooleanField(verbose_name='Repetible')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos')),
                ('automatico', models.NullBooleanField(verbose_name='Automático')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='main.Conjunto')),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjuntos',
            },
            bases=(main.mixins.SerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Formato')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            bases=(main.mixins.SerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UVT', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=255, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=255, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(max_length=255, verbose_name='Segundo apellido')),
                ('nit', models.IntegerField(verbose_name='N. Identificación Tributaria (NIT)')),
                ('nacionalidad', models.CharField(max_length=255, verbose_name='Nacionalidad')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='declaracion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones', to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='condicion',
            name='conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_set', to='main.Conjunto', verbose_name='Conjunto'),
        ),
        migrations.AddField(
            model_name='campo',
            name='conjunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='main.Conjunto', verbose_name='Conjunto'),
        ),
    ]
