# Generated by Django 2.0.7 on 2018-08-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaracion',
            options={'verbose_name': 'Declaración de Renta', 'verbose_name_plural': 'Declaraciones de Renta'},
        ),
        migrations.RemoveField(
            model_name='condicion',
            name='condiciones',
        ),
        migrations.RemoveField(
            model_name='condicion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='condicion',
            name='uvt',
        ),
        migrations.AddField(
            model_name='condicion',
            name='tipo_derecha',
            field=models.CharField(blank=True, choices=[('>', 'Mayor que'), ('<', 'Menor que'), ('=', 'Igual que'), ('>=', 'Mayor o igual que'), ('<=', 'Menor o igual que'), ('<>', 'Diferente que'), ('+', 'Suma'), ('*', 'Multiplicación'), ('/', 'División'), ('-', 'Resta')], max_length=1, verbose_name='Tipo Derecha'),
        ),
        migrations.AddField(
            model_name='condicion',
            name='tipo_izquierda',
            field=models.CharField(blank=True, choices=[('>', 'Mayor que'), ('<', 'Menor que'), ('=', 'Igual que'), ('>=', 'Mayor o igual que'), ('<=', 'Menor o igual que'), ('<>', 'Diferente que'), ('+', 'Suma'), ('*', 'Multiplicación'), ('/', 'División'), ('-', 'Resta')], max_length=1, verbose_name='Tipo Izquierda'),
        ),
        migrations.AddField(
            model_name='condicion',
            name='unidad_derecha',
            field=models.CharField(blank=True, choices=[('%', '%'), ('UVT', 'UVT')], max_length=1, verbose_name='Unidad Derecha'),
        ),
        migrations.AddField(
            model_name='condicion',
            name='unidad_izquierda',
            field=models.CharField(blank=True, choices=[('%', '%'), ('UVT', 'UVT')], max_length=1, verbose_name='Unidad Izquierda'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='izquierda',
            field=models.CharField(max_length=255, verbose_name='Izquierda'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Orden'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='condicion',
            name='valor_no',
        ),
        migrations.AddField(
            model_name='condicion',
            name='valor_no',
            field=models.ManyToManyField(related_name='_condicion_valor_no_+', to='main.Condicion', verbose_name='Valor NO'),
        ),
        migrations.RemoveField(
            model_name='condicion',
            name='valor_si',
        ),
        migrations.AddField(
            model_name='condicion',
            name='valor_si',
            field=models.ManyToManyField(related_name='_condicion_valor_si_+', to='main.Condicion', verbose_name='Valor SI'),
        ),
    ]
