# Generated by Django 2.0.7 on 2018-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180821_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicion',
            name='izquierda',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izquierda'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='tipo_derecha',
            field=models.CharField(blank=True, choices=[('>', 'Mayor que'), ('<', 'Menor que'), ('=', 'Igual que'), ('>=', 'Mayor o igual que'), ('<=', 'Menor o igual que'), ('<>', 'Diferente que'), ('+', 'Suma'), ('*', 'Multiplicación'), ('/', 'División'), ('-', 'Resta'), ('_vod', 'Void')], max_length=10, verbose_name='Tipo Derecha'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='tipo_izquierda',
            field=models.CharField(blank=True, choices=[('>', 'Mayor que'), ('<', 'Menor que'), ('=', 'Igual que'), ('>=', 'Mayor o igual que'), ('<=', 'Menor o igual que'), ('<>', 'Diferente que'), ('+', 'Suma'), ('*', 'Multiplicación'), ('/', 'División'), ('-', 'Resta'), ('_vod', 'Void')], max_length=10, verbose_name='Tipo Izquierda'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='unidad_derecha',
            field=models.CharField(blank=True, choices=[('%', '%'), ('UVT', 'UVT'), ('_vod', 'Void')], max_length=10, verbose_name='Unidad Derecha'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='unidad_izquierda',
            field=models.CharField(blank=True, choices=[('%', '%'), ('UVT', 'UVT'), ('_vod', 'Void')], max_length=10, verbose_name='Unidad Izquierda'),
        ),
    ]
