# Generated by Django 2.0.7 on 2018-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180828_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicion',
            name='valor_no',
            field=models.ManyToManyField(related_name='valores_no', to='main.Condicion', verbose_name='Valor NO'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='valor_si',
            field=models.ManyToManyField(related_name='valores_si', to='main.Condicion', verbose_name='Valor SI'),
        ),
    ]
